version: '3.9'

services:
  db:
    env_file:
      - ".env.dev"
    container_name: "database"
    image: postgres:latest
    networks:
      - botnet
    restart: always
#    ports:
#      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: "redis"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - botnet

  bot:
    container_name: "templatebot_dev"
    build:
      context: .
#    network_mode: host
    restart: always
    env_file:
      - ".env.dev"
    volumes:
      - .:/src
    networks:
      - botnet
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:

networks:
  botnet:
    driver: bridge
